name: leptisapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  xml: ^3.0.0
  flutter_redux: ^0.5.0
  intl: ^0.15.2
  url_launcher: ^3.0.0
  path_provider: ^1.3.0
  shared_preferences: ^0.4.0

  html: ^0.14.0+2
  html_plus: ^0.14.0+1
  flutter_markdown: ^0.2.0
  font_awesome_flutter: ^8.5.0
  http: ^0.12.0+2
  crypto: ^2.1.3
  cached_network_image: ^2.3.3
  flutter_cache_manager: ^1.1.1
  package_info: ^0.4.0+6
  logging: ^0.11.3+2
  gpx: ^0.0.1
  share: ^0.6.3+1
  strings: ^0.1.2
  flutter_map: ^0.10.1+1
  geolocator: ^5.1.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: WeatherIcons
      fonts:
        - asset: assets/fonts/weathericons-regular.ttf
          weight: 400
  assets:
    - assets/preloaded_data/theaters.xml

    - assets/preloaded_data/salidas_temporada.json
    - assets/preloaded_data/salidas_alternativo.json
    - assets/preloaded_data/escolta.json
    - assets/preloaded_data/eventos.json
    - assets/preloaded_data/about.txt

    - assets/preloaded_data/Trajano.gpx
    - assets/preloaded_data/ElPalmarDeTroya.gpx
    - assets/preloaded_data/AlcaláDeGuadaira.gpx
    - assets/preloaded_data/Arahal.gpx
    - assets/preloaded_data/Bucare.gpx
    - assets/preloaded_data/CortijoElRubio.gpx
    - assets/preloaded_data/TorresAlocaz.gpx


    - assets/images/leptis.png
    - assets/images/leptis_trans.png
    - assets/images/podio.png
    - assets/images/route_cover.png
    - assets/images/trianglify.png
    - assets/images/1x1_transparent.png
    - assets/images/powered_by_tmdb.png

    - assets/images/routes_cover/arahal.jpg
    - assets/images/routes_cover/cote.picture-400.jpg
    - assets/images/routes_cover/El-Viso-del-Alcor-3.jpg
    - assets/images/routes_cover/lospalacios.jpg
    - assets/images/routes_cover/pantano.jpg
    - assets/images/routes_cover/sevilla-alcala-de-guadaira.jpg
    - assets/images/routes_cover/trajano.jpg
    - assets/images/routes_cover/zarracatin.jpg
    - assets/images/routes_cover/lascabezas.jpg
    - assets/images/routes_cover/arroyo_dulce.jpg
    - assets/images/routes_cover/arroyo_hondo.jpg
    - assets/images/routes_cover/bucare.jpg
    - assets/images/routes_cover/carriles_bici_sevilla.jpg
    - assets/images/routes_cover/gomez_cardeña.jpg
    - assets/images/routes_cover/isla_minima.jpg
    - assets/images/routes_cover/Moron-Frontera.jpg
    - assets/images/routes_cover/torre_alocaz.jpg
    - assets/images/routes_cover/torre_bollo.jpg
    - assets/images/routes_cover/generica.jpg
    - assets/images/routes_cover/No_map.png
    - assets/images/routes_cover/generica1.jpg
    - assets/images/routes_cover/generica2.jpg
    - assets/images/routes_cover/generica3.jpg
    - assets/images/routes_cover/generica4.jpg
    - assets/images/routes_cover/generica5.jpg

    - assets/images/events/20anos_enverde.png
    - assets/images/events/andalucia28f.jpg
    - assets/images/events/fiesta_arbol.png
    - assets/images/events/media_centena.jpg
    - assets/images/events/plantacion_puertaverde.jpg
    - assets/images/events/semana_movilidad.jpg
    - assets/images/events/final_temporada.jpg